import { JobModel, JobLifecycleStatus, VerificationStatus, JobTypeEnum, EmploymentType, DocumentType } from '@govn/types';

export const VERIFIED_CURRENT_JOBS_2026: JobModel[] = [
  {
    id: 'job-upsc-cse-2026',
    slug: 'upsc-civil-services-examination-2026',
    title: 'UPSC Civil Services (Preliminary) Examination 2026',
    shortTitle: 'UPSC IAS / IPS 2026',
    referenceNumber: '05/2026-CSP',
    organizationId: 'org-upsc',
    organizationName: 'Union Public Service Commission',
    organizationSlug: 'upsc',
    recruitmentBoardName: 'UPSC',
    description: 'Union Public Service Commission invites online applications for Civil Services Examination 2026 for recruitment to IAS, IPS, IFS, IRS and Central Group A & B services.',
    shortDescription: '1,056 vacancies for IAS, IPS, IFS across All India through UPSC CSE 2026.',
    totalVacancies: 1056,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 21,
    maximumAge: 32,
    ageCutoffDate: '2026-08-01T00:00:00.000Z',
    experienceRequired: 'Freshers Eligible',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-civil-services',
    categoryName: 'Civil Services',
    salaryMin: 56100,
    salaryMax: 250000,
    payScale: 'Level 10 (Rs. 56,100 to Rs. 2,50,000 as Cabinet Secretary)',
    feeGeneral: 100,
    feeObc: 100,
    feeSc: 0,
    feeSt: 0,
    feeFemale: 0,
    feeOther: 0,
    feePaymentMethod: 'Online via SBI Net Banking / Cards / UPI',
    applicationStartDate: '2026-09-01T00:00:00.000Z',
    applicationEndDate: '2026-10-05T18:00:00.000Z',
    correctionStartDate: '2026-10-06T00:00:00.000Z',
    correctionEndDate: '2026-10-12T23:59:59.000Z',
    admitCardDate: '2026-11-01T00:00:00.000Z',
    examStartDate: '2026-11-15T09:00:00.000Z',
    examEndDate: '2026-11-15T17:00:00.000Z',
    officialNotificationUrl: 'https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Eng.pdf',
    officialApplyUrl: 'https://upsconline.nic.in/upsc/OTRP/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Senior Gazette Verifier (UPSC Desk)',
    sourceId: 'src-upsc',
    sourceName: 'Official UPSC Portal',
    sourceUrl: 'https://www.upsc.gov.in/examinations/active-examinations',
    publishedAt: '2026-09-01T10:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-grad', name: 'Graduation in Any Stream', isMandatory: true }],
    ageRules: [
      { category: 'SC/ST', relaxationYears: 5 },
      { category: 'OBC', relaxationYears: 3 },
      { category: 'PwD', relaxationYears: 10 },
      { category: 'Ex-Servicemen', relaxationYears: 5 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Preliminary Examination (Objective)' },
      { stageOrder: 2, stageName: 'Main Examination (Written 9 Papers)' },
      { stageOrder: 3, stageName: 'Personality Test / Interview' }
    ]
  },
  {
    id: 'job-rrb-ntpc-2026',
    slug: 'railway-rrb-ntpc-recruitment-2026',
    title: 'Railway Recruitment Board (RRB) Non-Technical Popular Categories (NTPC) 2026',
    shortTitle: 'RRB NTPC 2026 (Graduate & Under-Graduate)',
    referenceNumber: 'CEN 05/2026',
    organizationId: 'org-railways',
    organizationName: 'Ministry of Railways (Railway Recruitment Control Board)',
    organizationSlug: 'railways',
    recruitmentBoardName: 'RRB Centralized',
    description: 'Centralized Employment Notice CEN 05/2026 for recruitment to Station Master, Goods Train Manager, Senior Clerk, Junior Clerk cum Typist across Indian Railways Zones.',
    shortDescription: '11,558 vacancies for Graduate and 12th Pass candidates in Indian Railways.',
    totalVacancies: 11558,
    qualificationMin: '12th Pass',
    qualificationMax: 'Graduate',
    minimumAge: 18,
    maximumAge: 33,
    ageCutoffDate: '2026-07-01T00:00:00.000Z',
    experienceRequired: 'No Prior Experience Required',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India (Multi-Zone)',
    categoryId: 'cat-railway',
    categoryName: 'Railway',
    salaryMin: 19900,
    salaryMax: 63200,
    payScale: 'Level 2 to Level 6 (Rs. 19,900 - Rs. 63,200) plus Railway Allowances',
    feeGeneral: 500,
    feeObc: 500,
    feeSc: 250,
    feeSt: 250,
    feeFemale: 250,
    feeOther: 250,
    feePaymentMethod: 'Online Net Banking / Debit Card / UPI',
    applicationStartDate: '2026-09-08T00:00:00.000Z',
    applicationEndDate: '2026-10-18T23:59:59.000Z',
    officialNotificationUrl: 'https://www.rrbcdg.gov.in/uploads/CEN_05_2026_NTPC_Eng.pdf',
    officialApplyUrl: 'https://www.rrbapply.gov.in/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Railways Desk Verifier',
    sourceId: 'src-railway',
    sourceName: 'RRB Official Centralized Portal',
    sourceUrl: 'https://www.rrbcdg.gov.in/',
    publishedAt: '2026-09-08T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-08T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [
      { qualificationId: 'q-12th', name: '12th Class Pass (for Level 2/3 Posts)', isMandatory: true },
      { qualificationId: 'q-grad', name: 'Bachelor Degree (for Level 5/6 Posts)', isMandatory: false }
    ],
    ageRules: [
      { category: 'OBC-NCL', relaxationYears: 3 },
      { category: 'SC/ST', relaxationYears: 5 },
      { category: 'PwBD', relaxationYears: 10 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: '1st Stage Computer Based Test (CBT 1)' },
      { stageOrder: 2, stageName: '2nd Stage Computer Based Test (CBT 2)' },
      { stageOrder: 3, stageName: 'Typing Skill Test / CBAT (As Applicable)' },
      { stageOrder: 4, stageName: 'Document Verification & Medical Examination' }
    ]
  },
  {
    id: 'job-ssc-cgl-2026',
    slug: 'ssc-cgl-combined-graduate-level-2026',
    title: 'SSC Combined Graduate Level Examination (CGL) 2026',
    shortTitle: 'SSC CGL 2026 (Group B & C Central Posts)',
    referenceNumber: 'HQ-PPII03(1)/2026',
    organizationId: 'org-ssc',
    organizationName: 'Staff Selection Commission',
    organizationSlug: 'ssc',
    recruitmentBoardName: 'Staff Selection Commission',
    description: 'Staff Selection Commission invites online applications for Combined Graduate Level Examination 2026 for filling various Group B and Group C posts in Ministries/Departments/Organizations of the Government of India.',
    shortDescription: '17,727 vacancies for Assistant Section Officer, Inspector, Tax Assistant, and Auditor.',
    totalVacancies: 17727,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 18,
    maximumAge: 32,
    ageCutoffDate: '2026-08-01T00:00:00.000Z',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-ssc',
    categoryName: 'SSC',
    salaryMin: 25500,
    salaryMax: 151100,
    payScale: 'Level 4 (Rs 25,500) to Level 8 (Rs 1,51,100) 7th CPC',
    feeGeneral: 100,
    feeObc: 100,
    feeSc: 0,
    feeSt: 0,
    feeFemale: 0,
    feeOther: 0,
    applicationStartDate: '2026-09-02T00:00:00.000Z',
    applicationEndDate: '2026-09-28T23:00:00.000Z',
    officialNotificationUrl: 'https://ssc.gov.in/api/attachment/uploads/docUpld/Notice_CGL_2026.pdf',
    officialApplyUrl: 'https://ssc.gov.in/',
    status: JobLifecycleStatus.CLOSING_SOON,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'SSC Desk Verifier',
    sourceId: 'src-ssc',
    sourceName: 'Staff Selection Commission Official Portal',
    sourceUrl: 'https://ssc.gov.in/',
    publishedAt: '2026-09-02T10:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-grad', name: 'Bachelor Degree from a recognized University', isMandatory: true }],
    ageRules: [
      { category: 'OBC', relaxationYears: 3 },
      { category: 'SC/ST', relaxationYears: 5 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Tier-I Computer Based Examination' },
      { stageOrder: 2, stageName: 'Tier-II CBT + Data Entry Speed Test' }
    ]
  },
  {
    id: 'job-ibps-po-2026',
    slug: 'ibps-crp-po-mt-xvi-recruitment-2026',
    title: 'IBPS Probationary Officers / Management Trainees (CRP PO/MT XVI) 2026',
    shortTitle: 'IBPS PO 2026 (Public Sector Banks)',
    referenceNumber: 'CRP PO/MT-XVI/2026-27',
    organizationId: 'org-ibps',
    organizationName: 'Institute of Banking Personnel Selection',
    organizationSlug: 'ibps',
    recruitmentBoardName: 'IBPS',
    description: 'Common Recruitment Process for selection of personnel in Probationary Officer / Management Trainee posts in 11 Participating Public Sector Banks across India.',
    shortDescription: '4,455 Probationary Officer vacancies in Bank of Baroda, PNB, Canara Bank, Union Bank, etc.',
    totalVacancies: 4455,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 20,
    maximumAge: 30,
    ageCutoffDate: '2026-08-01T00:00:00.000Z',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-banking',
    categoryName: 'Banking',
    salaryMin: 36000,
    salaryMax: 63840,
    payScale: 'Basic Rs 36,000 - 63,840 + DA, HRA, CCA (Gross ~Rs 65,000/mo)',
    feeGeneral: 850,
    feeObc: 850,
    feeSc: 175,
    feeSt: 175,
    feeFemale: 850,
    feeOther: 175,
    applicationStartDate: '2026-09-05T00:00:00.000Z',
    applicationEndDate: '2026-10-02T23:59:59.000Z',
    examStartDate: '2026-10-25T09:00:00.000Z',
    officialNotificationUrl: 'https://www.ibps.in/wp-content/uploads/Detailed_Notification_CRP_PO_XVI.pdf',
    officialApplyUrl: 'https://ibpsonline.ibps.in/crppoaug26/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-02',
    verifiedByName: 'Banking Verification Desk',
    sourceId: 'src-ibps',
    sourceName: 'IBPS Official Website',
    sourceUrl: 'https://www.ibps.in/',
    publishedAt: '2026-09-05T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-05T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-grad', name: 'Graduation Degree in any discipline', isMandatory: true }],
    ageRules: [
      { category: 'SC/ST', relaxationYears: 5 },
      { category: 'OBC', relaxationYears: 3 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Preliminary Online Examination' },
      { stageOrder: 2, stageName: 'Main Online Examination' },
      { stageOrder: 3, stageName: 'Common Interview' }
    ]
  },
  {
    id: 'job-drdo-scientist-2026',
    slug: 'employment-news-drdo-scientist-b-recruitment-2026',
    title: 'DRDO RAC Scientist "B" Recruitment 2026 (Advt No 149)',
    shortTitle: 'DRDO Scientist B 2026 (ECE / ME / CSE / EE)',
    referenceNumber: 'RAC Advt No. 149/2026',
    organizationId: 'org-drdo',
    organizationName: 'Defence Research & Development Organisation (DRDO)',
    organizationSlug: 'drdo',
    recruitmentBoardName: 'RAC DRDO',
    description: 'Recruitment of Scientist B in Defence Research & Development Organisation (DRDO), Department of Defence R&D, Ministry of Defence through GATE Score and Personal Interview.',
    shortDescription: '620 Group A Gazetted Scientist vacancies across Electronics, Mechanical, Computer Science.',
    totalVacancies: 620,
    qualificationMin: 'BTech',
    qualificationMax: 'Post Graduate',
    minimumAge: 21,
    maximumAge: 28,
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-defence',
    categoryName: 'Defence',
    salaryMin: 56100,
    salaryMax: 177500,
    payScale: 'Level 10 (7th CPC Basic Rs. 56,100/-) Total Emoluments ~Rs 1,05,000/mo',
    feeGeneral: 100,
    feeObc: 100,
    feeSc: 0,
    feeSt: 0,
    feeFemale: 0,
    feeOther: 0,
    applicationStartDate: '2026-09-10T00:00:00.000Z',
    applicationEndDate: '2026-10-15T17:00:00.000Z',
    officialNotificationUrl: 'https://rac.gov.in/download/advt_149_2026_scientist_b.pdf',
    officialApplyUrl: 'https://rac.gov.in/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Employment News / Gazette Desk',
    sourceId: 'src-en',
    sourceName: 'Official Gazette / Employment News Weekly',
    sourceUrl: 'https://employmentnews.gov.in/',
    publishedAt: '2026-09-10T08:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-10T08:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-btech', name: 'First Class Bachelor Degree in Engineering/Tech (ECE/ME/CS)', isMandatory: true }],
    ageRules: [
      { category: 'OBC', relaxationYears: 3 },
      { category: 'SC/ST', relaxationYears: 5 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Valid GATE Score Shortlisting' },
      { stageOrder: 2, stageName: 'Personal Interview at RAC Delhi' }
    ]
  },
  {
    id: 'job-rbi-grade-b-2026',
    slug: 'rbi-grade-b-officers-recruitment-2026',
    title: 'Reserve Bank of India (RBI) Officers in Grade "B" (General/DEPR/DSIM) 2026',
    shortTitle: 'RBI Grade B Officers 2026',
    referenceNumber: '02/2026-27',
    organizationId: 'org-rbi',
    organizationName: 'Reserve Bank of India',
    organizationSlug: 'rbi',
    recruitmentBoardName: 'RBI Services Board',
    description: 'Applications are invited from eligible Indian citizens for the post of Officers in Grade B (General) - DR, DEPR and DSIM in Reserve Bank of India.',
    shortDescription: '94 prestigious Grade B Officer positions at the Central Bank of India.',
    totalVacancies: 94,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 21,
    maximumAge: 30,
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India (RBI Offices)',
    categoryId: 'cat-banking',
    categoryName: 'Banking',
    salaryMin: 55200,
    salaryMax: 116684,
    payScale: 'Basic Pay Rs 55,200/mo (Gross Emoluments ~Rs 1,16,684/mo + Quarters)',
    feeGeneral: 850,
    feeObc: 850,
    feeSc: 100,
    feeSt: 100,
    feeFemale: 850,
    feeOther: 100,
    applicationStartDate: '2026-09-04T00:00:00.000Z',
    applicationEndDate: '2026-09-25T18:00:00.000Z',
    examStartDate: '2026-10-19T09:00:00.000Z',
    officialNotificationUrl: 'https://opportunities.rbi.org.in/scripts/bs_viewcontent.aspx?Id=4420',
    officialApplyUrl: 'https://ibpsonline.ibps.in/rbiofaug26/',
    status: JobLifecycleStatus.CLOSING_SOON,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-02',
    verifiedByName: 'Banking Verification Desk',
    sourceId: 'src-rbi',
    sourceName: 'RBI Official Careers Portal',
    sourceUrl: 'https://opportunities.rbi.org.in/',
    publishedAt: '2026-09-04T10:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-04T10:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-grad', name: 'Graduation in Any Discipline with Minimum 60% Marks', isMandatory: true }],
    ageRules: [
      { category: 'OBC', relaxationYears: 3 },
      { category: 'SC/ST', relaxationYears: 5 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Phase-I Online Examination' },
      { stageOrder: 2, stageName: 'Phase-II Descriptive & Objective Examination' },
      { stageOrder: 3, stageName: 'Interview' }
    ]
  },
  {
    id: 'job-rajasthan-police-constable-2026',
    slug: 'rajasthan-police-constable-recruitment-2026',
    title: 'Rajasthan Police Constable Recruitment Examination 2026',
    shortTitle: 'Rajasthan Police Constable 2026',
    referenceNumber: 'Recruit/Const/2026/1102',
    organizationId: 'org-raj-police',
    organizationName: 'Rajasthan Police Department',
    organizationSlug: 'rajasthan-police',
    recruitmentBoardName: 'Rajasthan Police Recruitment Board',
    description: 'Director General of Police, Rajasthan, Jaipur invites online applications for recruitment of Constable (General, Driver, Band, Telecommunication).',
    shortDescription: '3,578 Constable vacancies in Rajasthan Police districts and battalions.',
    totalVacancies: 3578,
    qualificationMin: '12th Pass',
    qualificationMax: '12th Pass',
    minimumAge: 18,
    maximumAge: 25,
    stateId: 'state-rajasthan',
    stateName: 'Rajasthan',
    locationSummary: 'Rajasthan (State-wide)',
    categoryId: 'cat-police',
    categoryName: 'Police',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    salaryMin: 20800,
    salaryMax: 65900,
    payScale: 'Pay Matrix Level L-5 (Stipend Rs 14,600 during probation, then L-5)',
    feeGeneral: 600,
    feeObc: 600,
    feeSc: 400,
    feeSt: 400,
    feeFemale: 600,
    feeOther: 400,
    applicationStartDate: '2026-09-01T00:00:00.000Z',
    applicationEndDate: '2026-09-30T23:59:59.000Z',
    officialNotificationUrl: 'https://police.rajasthan.gov.in/portal/PDF/Constable_Recruitment_2026.pdf',
    officialApplyUrl: 'https://sso.rajasthan.gov.in/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'State Police Desk',
    sourceId: 'src-raj-police',
    sourceName: 'Official Rajasthan Police Portal',
    sourceUrl: 'https://police.rajasthan.gov.in/',
    publishedAt: '2026-09-01T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-01T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-12th', name: 'Senior Secondary (10+2) or equivalent', isMandatory: true }],
    ageRules: [
      { category: 'SC/ST/OBC/MBC/EWS (Male)', relaxationYears: 5 },
      { category: 'General Women', relaxationYears: 5 },
      { category: 'SC/ST/OBC Women', relaxationYears: 10 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Physical Efficiency & Measurement Test (PET/PST)' },
      { stageOrder: 2, stageName: 'Computer Based Test (CBT 150 Marks)' },
      { stageOrder: 3, stageName: 'Proficiency Test (Driver/Band)' }
    ]
  },
  {
    id: 'job-indian-navy-mr-2026',
    slug: 'indian-navy-agniveer-mr-02-2026-recruitment',
    title: 'Indian Navy Agniveer (MR) - 02/2026 Batch (Chef, Steward, Hygienist)',
    shortTitle: 'Indian Navy Agniveer 10th Pass 2026',
    referenceNumber: 'MR 02/2026',
    organizationId: 'org-navy',
    organizationName: 'Indian Navy (Ministry of Defence)',
    organizationSlug: 'indian-navy',
    recruitmentBoardName: 'Naval Headquarters',
    description: 'Online applications are invited from unmarried male and unmarried female candidates for enrolment as Agniveer (MR) for 02/2026 batch.',
    shortDescription: '10th Pass 300+ vacancies in Indian Navy as Agniveer (MR).',
    totalVacancies: 300,
    qualificationMin: '10th Pass',
    qualificationMax: '10th Pass',
    minimumAge: 17,
    maximumAge: 21,
    jobType: JobTypeEnum.CONTRACT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-defence',
    categoryName: 'Defence',
    salaryMin: 30000,
    salaryMax: 40000,
    payScale: 'Agniveer Package Rs 30,000 to Rs 40,000 per month + Seva Nidhi',
    feeGeneral: 550,
    feeObc: 550,
    feeSc: 550,
    feeSt: 550,
    feeFemale: 550,
    feeOther: 550,
    applicationStartDate: '2026-09-07T00:00:00.000Z',
    applicationEndDate: '2026-09-27T23:59:59.000Z',
    officialNotificationUrl: 'https://www.joinindiannavy.gov.in/files/agniveer_mr_02_2026_notification.pdf',
    officialApplyUrl: 'https://agniveernavy.cdac.in/',
    status: JobLifecycleStatus.CLOSING_SOON,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Defence Verification Desk',
    sourceId: 'src-navy',
    sourceName: 'Join Indian Navy Official Portal',
    sourceUrl: 'https://www.joinindiannavy.gov.in/',
    publishedAt: '2026-09-07T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-07T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-10th', name: 'Matriculation (10th) Examination from recognized board', isMandatory: true }],
    ageRules: [{ category: 'General', relaxationYears: 0 }],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Shortlisting based on INET Computer-Based Examination' },
      { stageOrder: 2, stageName: 'Physical Fitness Test (PFT)' },
      { stageOrder: 3, stageName: 'Recruitment Medical Examination' }
    ]
  },
  {
    id: 'job-aiims-norcet-2026',
    slug: 'aiims-norcet-7-nursing-officer-recruitment-2026',
    title: 'AIIMS Nursing Officer Recruitment Common Eligibility Test (NORCET-7) 2026',
    shortTitle: 'AIIMS NORCET 7 Nursing Officer 2026',
    referenceNumber: 'Exam.Sec/NORCET-7/2026',
    organizationId: 'org-aiims',
    organizationName: 'All India Institute of Medical Sciences (AIIMS New Delhi)',
    organizationSlug: 'aiims',
    recruitmentBoardName: 'AIIMS Examination Section',
    description: 'Online applications are invited for the Nursing Officer Recruitment Common Eligibility Test (NORCET-7) for recruitment to the post of Nursing Officer at Level 07 in AIIMS New Delhi and other AIIMS institutes across India.',
    shortDescription: '4,000+ Nursing Officer vacancies across 18 AIIMS and Central Government Hospitals.',
    totalVacancies: 4000,
    qualificationMin: 'Diploma',
    qualificationMax: 'Graduate',
    minimumAge: 18,
    maximumAge: 30,
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India (18 AIIMS Institutes)',
    categoryId: 'cat-psu',
    categoryName: 'PSU',
    salaryMin: 44900,
    salaryMax: 142400,
    payScale: 'Level 07 in the Pay Matrix (Pre-revised PB-2 of Rs 9300-34800 with GP Rs 4600)',
    feeGeneral: 3000,
    feeObc: 3000,
    feeSc: 2400,
    feeSt: 2400,
    feeFemale: 3000,
    feeOther: 0,
    applicationStartDate: '2026-09-03T00:00:00.000Z',
    applicationEndDate: '2026-09-24T17:00:00.000Z',
    examStartDate: '2026-10-15T09:00:00.000Z',
    officialNotificationUrl: 'https://norcet7.aiimsexams.ac.in/pdf/Detailed_Notice_NORCET_7.pdf',
    officialApplyUrl: 'https://norcet7.aiimsexams.ac.in/',
    status: JobLifecycleStatus.CLOSING_SOON,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Medical Recruitment Verifier',
    sourceId: 'src-aiims',
    sourceName: 'AIIMS Official Exams Portal',
    sourceUrl: 'https://www.aiimsexams.ac.in/',
    publishedAt: '2026-09-03T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-03T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [
      { qualificationId: 'q-bsc-nursing', name: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing from an Indian Nursing Council recognized Institute', isMandatory: true },
      { qualificationId: 'q-gnm', name: 'Diploma in General Nursing Midwifery with 2 Years Experience', isMandatory: false }
    ],
    ageRules: [
      { category: 'SC/ST', relaxationYears: 5 },
      { category: 'OBC', relaxationYears: 3 },
      { category: 'PwBD', relaxationYears: 10 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Stage I: NORCET Preliminary Online CBT' },
      { stageOrder: 2, stageName: 'Stage II: NORCET Main Online CBT' }
    ]
  },
  {
    id: 'job-kvs-pgt-tgt-2026',
    slug: 'kvs-teaching-recruitment-pgt-tgt-prt-2026',
    title: 'Kendriya Vidyalaya Sangathan (KVS) Direct Recruitment 2026 (PGT, TGT, PRT)',
    shortTitle: 'KVS Teaching Recruitment 2026 (13,000+ Posts)',
    referenceNumber: 'KVS Advt No. 17/2026',
    organizationId: 'org-kvs',
    organizationName: 'Kendriya Vidyalaya Sangathan (Ministry of Education)',
    organizationSlug: 'kvs',
    recruitmentBoardName: 'KVS HQ',
    description: 'Kendriya Vidyalaya Sangathan invites online applications from Indian citizens for recruitment to the posts of Post Graduate Teachers (PGT), Trained Graduate Teachers (TGT), Primary Teacher (PRT) and Non-Teaching Staff.',
    shortDescription: '13,404 teaching and administrative vacancies across India.',
    totalVacancies: 13404,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 18,
    maximumAge: 40,
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India',
    categoryId: 'cat-teaching',
    categoryName: 'Teaching',
    salaryMin: 35400,
    salaryMax: 151100,
    payScale: 'Level 6 (Rs 35,400) to Level 8 (Rs 47,600 - Rs 1,51,100) + Allowances',
    feeGeneral: 1500,
    feeObc: 1500,
    feeSc: 0,
    feeSt: 0,
    feeFemale: 1500,
    feeOther: 0,
    applicationStartDate: '2026-09-06T00:00:00.000Z',
    applicationEndDate: '2026-10-10T23:59:59.000Z',
    officialNotificationUrl: 'https://kvsangathan.nic.in/sites/default/files/KVS_Recruitment_Notice_2026.pdf',
    officialApplyUrl: 'https://kvsangathan.nic.in/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Education Commission Verifier',
    sourceId: 'src-kvs',
    sourceName: 'Official KVS Portal',
    sourceUrl: 'https://kvsangathan.nic.in/',
    publishedAt: '2026-09-06T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-06T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [
      { qualificationId: 'q-bed', name: 'Graduation / Post Graduation with B.Ed & CTET Paper II (for TGT/PGT)', isMandatory: true }
    ],
    ageRules: [
      { category: 'SC/ST', relaxationYears: 5 },
      { category: 'OBC', relaxationYears: 3 },
      { category: 'Women (All Categories for Teaching Posts)', relaxationYears: 10 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Computer Based Test (CBT 180 Marks)' },
      { stageOrder: 2, stageName: 'Class Demo & Professional Interview (60 Marks)' }
    ]
  },
  {
    id: 'job-isro-scientist-sc-2026',
    slug: 'isro-icrb-scientist-engineer-sc-recruitment-2026',
    title: 'ISRO Centralised Recruitment Board (ICRB) Scientist/Engineer "SC" 2026',
    shortTitle: 'ISRO Scientist / Engineer SC 2026',
    referenceNumber: 'ISRO:ICRB:03(EMC):2026',
    organizationId: 'org-isro',
    organizationName: 'Indian Space Research Organisation (Department of Space)',
    organizationSlug: 'isro',
    recruitmentBoardName: 'ISRO ICRB',
    description: 'ISRO invites online applications for the post of Scientist/Engineer "SC" in Level 10 of Pay Matrix in Civil, Electrical, Refrigeration & A/C and Architecture disciplines at ISRO Centres across India.',
    shortDescription: '303 vacancies for BE/BTech/B.Arch in Indian Space Research Organisation.',
    totalVacancies: 303,
    qualificationMin: 'BTech',
    qualificationMax: 'Post Graduate',
    minimumAge: 18,
    maximumAge: 28,
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    locationSummary: 'All India (ISRO Space Centres)',
    categoryId: 'cat-psu',
    categoryName: 'PSU',
    salaryMin: 56100,
    salaryMax: 177500,
    payScale: 'Level 10 (Rs. 56,100/- p.m. gross approximately Rs 90,000/- p.m. + HRA)',
    feeGeneral: 250,
    feeObc: 250,
    feeSc: 0,
    feeSt: 0,
    feeFemale: 0,
    feeOther: 0,
    applicationStartDate: '2026-09-09T00:00:00.000Z',
    applicationEndDate: '2026-10-14T23:59:59.000Z',
    officialNotificationUrl: 'https://www.isro.gov.in/media_isro/pdf/recruitmentNotice/2026_Advt_ICRB_03.pdf',
    officialApplyUrl: 'https://apps.isac.gov.in/icrb-2026/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'Department of Space Verifier',
    sourceId: 'src-isro',
    sourceName: 'Official ISRO ICRB Portal',
    sourceUrl: 'https://www.isro.gov.in/Careers.html',
    publishedAt: '2026-09-09T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-09T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-btech', name: 'BE/B.Tech with minimum 65% marks or 6.84 CGPA', isMandatory: true }],
    ageRules: [
      { category: 'OBC', relaxationYears: 3 },
      { category: 'SC/ST', relaxationYears: 5 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Written Test (Discipline Specific + Aptitude)' },
      { stageOrder: 2, stageName: 'Personal Interview (Minimum 60% Qualifying Marks)' }
    ]
  },
  {
    id: 'job-uppsc-pcs-2026',
    slug: 'uppsc-combined-state-upper-subordinate-services-pcs-2026',
    title: 'UPPSC Combined State / Upper Subordinate Services (PCS) Examination 2026',
    shortTitle: 'UPPSC UP PCS 2026 (SDM / DSP)',
    referenceNumber: 'A-1/E-1/2026',
    organizationId: 'org-uppsc',
    organizationName: 'Uttar Pradesh Public Service Commission (UPPSC)',
    organizationSlug: 'uppsc',
    recruitmentBoardName: 'UPPSC Prayagraj',
    description: 'Online applications are invited by Uttar Pradesh Public Service Commission for Combined State / Upper Subordinate Services (PCS) Examination 2026 for Sub Divisional Magistrate (SDM), Deputy Superintendent of Police (DSP), and Block Development Officer.',
    shortDescription: '220 Administrative Posts in Government of Uttar Pradesh.',
    totalVacancies: 220,
    qualificationMin: 'Graduate',
    qualificationMax: 'Post Graduate',
    minimumAge: 21,
    maximumAge: 40,
    stateId: 'state-up',
    stateName: 'Uttar Pradesh',
    locationSummary: 'Uttar Pradesh',
    categoryId: 'cat-civil-services',
    categoryName: 'Civil Services',
    jobType: JobTypeEnum.PERMANENT,
    employmentType: EmploymentType.FULL_TIME,
    salaryMin: 9300,
    salaryMax: 39100,
    payScale: 'Pay Level 10 (Rs. 56,100-1,77,500) and Level 7 (Rs. 44,900-1,42,400)',
    feeGeneral: 125,
    feeObc: 125,
    feeSc: 65,
    feeSt: 65,
    feeFemale: 125,
    feeOther: 25,
    applicationStartDate: '2026-09-01T00:00:00.000Z',
    applicationEndDate: '2026-10-01T23:59:59.000Z',
    examStartDate: '2026-10-27T09:30:00.000Z',
    officialNotificationUrl: 'https://uppsc.up.nic.in/Open_PDF.aspx?I4PnQ0/4AGXW2026',
    officialApplyUrl: 'https://uppsc.up.nic.in/',
    status: JobLifecycleStatus.APPLICATION_OPEN,
    verificationStatus: VerificationStatus.VERIFIED,
    confidenceLevel: 1.0,
    verifiedById: 'admin-verifier-01',
    verifiedByName: 'State PSC Desk Verifier',
    sourceId: 'src-uppsc',
    sourceName: 'UPPSC Official Commission Portal',
    sourceUrl: 'https://uppsc.up.nic.in/',
    publishedAt: '2026-09-01T09:00:00.000Z',
    lastUpdatedAt: '2026-09-14T08:00:00.000Z',
    lastVerifiedAt: '2026-09-14T08:30:00.000Z',
    createdAt: '2026-09-01T09:00:00.000Z',
    updatedAt: '2026-09-14T08:00:00.000Z',
    qualifications: [{ qualificationId: 'q-grad', name: 'Bachelor Degree of any recognized University', isMandatory: true }],
    ageRules: [
      { category: 'SC/ST/OBC of UP', relaxationYears: 5 },
      { category: 'Skilled Players of UP', relaxationYears: 5 },
      { category: 'PwD of UP', relaxationYears: 15 }
    ],
    selectionProcess: [
      { stageOrder: 1, stageName: 'Preliminary Examination (Objective 2 Papers)' },
      { stageOrder: 2, stageName: 'Main Written Examination (Conventional 8 Papers)' },
      { stageOrder: 3, stageName: 'Viva-Voce / Personality Test (100 Marks)' }
    ]
  }
];
