export enum JobLifecycleStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  VERIFIED = 'VERIFIED',
  PUBLISHED = 'PUBLISHED',
  APPLICATION_OPEN = 'APPLICATION_OPEN',
  CLOSING_SOON = 'CLOSING_SOON',
  APPLICATION_CLOSED = 'APPLICATION_CLOSED',
  CORRECTION_OPEN = 'CORRECTION_OPEN',
  ADMIT_CARD_AVAILABLE = 'ADMIT_CARD_AVAILABLE',
  EXAM_SCHEDULED = 'EXAM_SCHEDULED',
  EXAM_COMPLETED = 'EXAM_COMPLETED',
  ANSWER_KEY_AVAILABLE = 'ANSWER_KEY_AVAILABLE',
  RESULT_DECLARED = 'RESULT_DECLARED',
  FINAL_RESULT = 'FINAL_RESULT',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  AUTO_EXTRACTED = 'AUTO_EXTRACTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  CONFLICT_DETECTED = 'CONFLICT_DETECTED',
}

export enum SourceTrustLevel {
  LEVEL_1_PRIMARY_OFFICIAL = 'LEVEL_1_PRIMARY_OFFICIAL',
  LEVEL_2_GOVERNMENT_AGGREGATOR = 'LEVEL_2_GOVERNMENT_AGGREGATOR',
  LEVEL_3_SECONDARY = 'LEVEL_3_SECONDARY',
  LEVEL_4_DISCOVERY_ONLY = 'LEVEL_4_DISCOVERY_ONLY',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  EDITOR = 'EDITOR',
  VERIFIER = 'VERIFIER',
  SEO_MANAGER = 'SEO_MANAGER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  SUPPORT = 'SUPPORT',
  DATA_OPERATOR = 'DATA_OPERATOR',
}

export enum DocumentType {
  ADVERTISEMENT = 'ADVERTISEMENT',
  NOTIFICATION = 'NOTIFICATION',
  CORRIGENDUM = 'CORRIGENDUM',
  ADDENDUM = 'ADDENDUM',
  SYLLABUS = 'SYLLABUS',
  ADMIT_CARD_NOTICE = 'ADMIT_CARD_NOTICE',
  RESULT_NOTICE = 'RESULT_NOTICE',
  ANSWER_KEY = 'ANSWER_KEY',
  OTHER = 'OTHER',
}

export enum ChangeType {
  DEADLINE_CHANGED = 'DEADLINE_CHANGED',
  VACANCY_CHANGED = 'VACANCY_CHANGED',
  FEE_CHANGED = 'FEE_CHANGED',
  AGE_LIMIT_CHANGED = 'AGE_LIMIT_CHANGED',
  EXAM_DATE_RESCHEDULED = 'EXAM_DATE_RESCHEDULED',
  ELIGIBILITY_UPDATED = 'ELIGIBILITY_UPDATED',
  CORRIGENDUM_ISSUED = 'CORRIGENDUM_ISSUED',
  APPLICATION_LINK_UPDATED = 'APPLICATION_LINK_UPDATED',
  RECRUITMENT_CANCELLED = 'RECRUITMENT_CANCELLED',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
  INTERNSHIP = 'INTERNSHIP',
}

export enum JobTypeEnum {
  PERMANENT = 'PERMANENT',
  CONTRACT = 'CONTRACT',
  DEPUTATION = 'DEPUTATION',
  APPRENTICESHIP = 'APPRENTICESHIP',
}
